version: "2"
services:
  mib-backend-node:
    image: "node:8"
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/home/node/app
    ports:
      - "3000:3000"
    command: "npm run dev"
    depends_on:
      - mib-backend-db
    stdin_open: true
    tty: true
  mib-backend-db:
    image: "mysql:5.7"
    environment:
      MYSQL_ROOT_PASSWORD: root_password_not_secret
    ports:
      - "3306:3306"
  mib-backend-pma:
    depends_on:
      - mib-backend-db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mib-backend-db
      MYSQL_ROOT_PASSWORD: root_password_not_secret
